#!/bin/bash

(. ./finder.sh)
(. ./cldt.sh)
# (. ./screensavers.sh)
(. ./touch_id.sh)
(. ./brew.sh)
(. ./zsh.sh)
(. ./clone-dotfiles.sh)
(. ./firefox.sh)
(. ./git.sh)
(. ./nvm.sh)
(. ./rbenv.sh)
(. ./vim.sh)
(. ./mas.sh)
(. ./misc.sh)
(. ./adobe-cc.sh)
(. ./large-downloads.sh)
